<a href="https://colab.research.google.com/github/ArunimaSaji/EDA/blob/main/missing_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/missing_data1.csv')
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       120     479.0
2         60  '2020/12/03'    103       120     340.0
3         45  '2020/12/04'    109       120     282.4
4         45  '2020/12/05'    117       120     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       120     374.0
7        450  '2020/12/08'    104       120     253.3
8         30  '2020/12/09'    109       120     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       120     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       120     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       120     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       120     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       120       NaN
29        60  '2020/12/29'    100       120     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [54]:
df.shape

(32, 5)

In [55]:
df.size

160

In [56]:
df.dtypes

Duration      int64
Date         object
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [57]:
df.isna().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [58]:
print(df['Duration'].value_counts())
df['Duration'].unique()

Duration
60     24
45      6
450     1
30      1
Name: count, dtype: int64

array([ 60,  45, 450,  30])

In [59]:
print(df['Date'].value_counts())
print(df['Date'].unique())

Date
'2020/12/12'    2
'2020/12/01'    1
'2020/12/03'    1
'2020/12/04'    1
'2020/12/05'    1
'2020/12/02'    1
'2020/12/06'    1
'2020/12/07'    1
'2020/12/09'    1
'2020/12/08'    1
'2020/12/10'    1
'2020/12/11'    1
'2020/12/13'    1
'2020/12/14'    1
'2020/12/15'    1
'2020/12/16'    1
'2020/12/17'    1
'2020/12/18'    1
'2020/12/19'    1
'2020/12/20'    1
'2020/12/21'    1
'2020/12/23'    1
'2020/12/24'    1
'2020/12/25'    1
20201226        1
'2020/12/27'    1
'2020/12/28'    1
'2020/12/29'    1
'2020/12/30'    1
'2020/12/31'    1
Name: count, dtype: int64
["'2020/12/01'" "'2020/12/02'" "'2020/12/03'" "'2020/12/04'"
 "'2020/12/05'" "'2020/12/06'" "'2020/12/07'" "'2020/12/08'"
 "'2020/12/09'" "'2020/12/10'" "'2020/12/11'" "'2020/12/12'"
 "'2020/12/13'" "'2020/12/14'" "'2020/12/15'" "'2020/12/16'"
 "'2020/12/17'" "'2020/12/18'" "'2020/12/19'" "'2020/12/20'"
 "'2020/12/21'" nan "'2020/12/23'" "'2020/12/24'" "'2020/12/25'"
 '20201226' "'2020/12/27'" "'2020/12/28'" "'2020/12/29'" "'2020/12/30'"
 "'2020/12/31'"]

In [60]:
print(df['Calories'].value_counts())
df['Calories'].unique()

Calories
300.0    3
250.7    2
243.0    2
340.0    1
479.0    1
406.0    1
374.0    1
253.3    1
282.4    1
409.1    1
269.0    1
195.1    1
345.3    1
329.3    1
379.3    1
275.0    1
215.2    1
323.0    1
364.2    1
282.0    1
246.0    1
334.5    1
250.0    1
241.0    1
280.0    1
380.3    1
Name: count, dtype: int64

array([409.1, 479. , 340. , 282.4, 406. , 300. , 374. , 253.3, 195.1,
       269. , 329.3, 250.7, 345.3, 379.3, 275. , 215.2,   nan, 323. ,
       243. , 364.2, 282. , 246. , 334.5, 250. , 241. , 280. , 380.3])

In [61]:
df.columns

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [62]:
lst=['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories']
for i in lst:
  print('_'*90)
  print(df[i].unique())

__________________________________________________________________________________________
[ 60  45 450  30]
__________________________________________________________________________________________
["'2020/12/01'" "'2020/12/02'" "'2020/12/03'" "'2020/12/04'"
 "'2020/12/05'" "'2020/12/06'" "'2020/12/07'" "'2020/12/08'"
 "'2020/12/09'" "'2020/12/10'" "'2020/12/11'" "'2020/12/12'"
 "'2020/12/13'" "'2020/12/14'" "'2020/12/15'" "'2020/12/16'"
 "'2020/12/17'" "'2020/12/18'" "'2020/12/19'" "'2020/12/20'"
 "'2020/12/21'" nan "'2020/12/23'" "'2020/12/24'" "'2020/12/25'"
 '20201226' "'2020/12/27'" "'2020/12/28'" "'2020/12/29'" "'2020/12/30'"
 "'2020/12/31'"]
__________________________________________________________________________________________
[110 117 103 109 102 104  98 100 106  90  97 108 130 105  92]
__________________________________________________________________________________________
[130 120 127 124 128 123 112 125 119 101 126 118 129 115]
__________________________________________________________________________________________
[409.1 479.  340.  282.4 406.  300.  374.  253.3 195.1 269.  329.3 250.7
 345.3 379.3 275.  215.2   nan 323.  243.  364.2 282.  246.  334.5 250.
 241.  280.  380.3]

In [63]:
df['Duration']=df['Duration'].replace(450,45)
print(df['Duration'].unique())

[60 45 30]

In [64]:
df['Date'].isna().sum()

np.int64(1)

In [65]:
df['Date']=df['Date'].replace('20201226',"'2020/12/26'")

In [66]:
df['Date'].isna().sum()

np.int64(1)

In [68]:
df['Date']=df['Date'].fillna(df['Date'].mode()[0])
df['Date'].isna().sum()

np.int64(0)

In [69]:
df.isna().sum()

Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [70]:
df['Calories']=df['Calories'].fillna(df['Calories'].mean())
df['Calories'].isna().sum()

np.int64(0)

In [71]:
df.isna().sum()

Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [72]:
df=pd.read_csv('/content/heart_missining.csv')
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125.0,212,0,NaN,168.0,0,1.0,2,2.0,3.0,0
1,53,1,0,140.0,203,1,0.0,155.0,1,3.1,0,0.0,3.0,0
2,70,1,0,145.0,174,0,1.0,125.0,1,2.6,0,0.0,3.0,0
3,61,1,0,148.0,203,0,1.0,NaN,0,0.0,2,1.0,3.0,0
4,62,0,0,138.0,294,1,1.0,106.0,0,1.9,1,3.0,2.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140.0,221,0,1.0,164.0,1,0.0,2,0.0,2.0,1
1021,60,1,0,125.0,258,0,0.0,141.0,1,2.8,1,1.0,3.0,0
1022,47,1,0,110.0,275,0,0.0,118.0,1,1.0,1,1.0,2.0,0
1023,50,0,0,110.0,254,0,0.0,159.0,0,0.0,2,0.0,2.0,1
1024,54,1,0,120.0,188,0,1.0,113.0,0,1.4,1,1.0,3.0,0

In [73]:
df.size

14350

In [74]:
df.shape

(1025, 14)

In [75]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps    float64
chol          int64
fbs           int64
restecg     float64
thalach     float64
exang         int64
oldpeak     float64
slope         int64
ca          float64
thal        float64
target        int64
dtype: object

In [76]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1024.000000,1025.00000,1025.000000,1024.000000,1024.000000,1025.000000,1025.000000,1025.000000,1023.000000,1024.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.603516,246.00000,0.149268,0.529297,149.102539,0.336585,1.071512,1.385366,0.752688,2.324219,0.513171
std,9.072290,0.460373,1.029641,17.523313,51.59251,0.356527,0.527931,23.013962,0.472772,1.175053,0.617755,1.029140,0.620881,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [77]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [78]:
l=['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']
for i in l:
        print('_'*100)
        print(df[i].unique())

____________________________________________________________________________________________________
[52 53 70 61 62 58 55 46 54 71 43 34 51 50 60 67 45 63 42 44 56 57 59 64
 65 41 66 38 49 48 29 37 47 68 76 40 39 77 69 35 74]
____________________________________________________________________________________________________
[1 0]
____________________________________________________________________________________________________
[0 1 2 3]
____________________________________________________________________________________________________
[125. 140. 145. 148. 138. 100. 114. 160. 120. 122. 112. 132. 118. 128.
  nan 124. 106. 104. 135. 130. 136. 180. 129. 150. 178. 146. 117. 152.
 154. 170. 134. 174. 144. 108. 123. 110. 142. 126. 192. 115.  94. 200.
 165. 102. 105. 155. 172. 164. 156. 101.]
____________________________________________________________________________________________________
[212 203 174 294 248 318 289 249 286 149 341 210 298 204 308 266 244 211
 185 223 208 252 209 307 233 319 256 327 169 131 269 196 231 213 271 263
 229 360 258 330 342 226 228 278 230 283 241 175 188 217 193 245 232 299
 288 197 315 215 164 326 207 177 257 255 187 201 220 268 267 236 303 282
 126 309 186 275 281 206 335 218 254 295 417 260 240 302 192 225 325 235
 274 234 182 167 172 321 300 199 564 157 304 222 184 354 160 247 239 246
 409 293 180 250 221 200 227 243 311 261 242 205 306 219 353 198 394 183
 237 224 265 313 340 259 270 216 264 276 322 214 273 253 176 284 305 168
 407 290 277 262 195 166 178 141]
____________________________________________________________________________________________________
[0 1]
____________________________________________________________________________________________________
[nan  0.  1.  2.]
____________________________________________________________________________________________________
[168. 155. 125.  nan 106. 122. 140. 145. 144. 116. 136. 192. 156. 142.
 109. 162. 165. 148. 172. 173. 146. 179. 152. 117. 115. 112. 163. 147.
 182. 105. 150. 151. 169. 166. 178. 132. 160. 123. 139. 111. 180. 164.
 202. 157. 159. 170. 138. 175. 158. 126. 143. 141. 167.  95. 190. 118.
 103. 181. 108. 177. 134. 120. 171. 149. 154. 153.  88. 174. 114. 195.
 133.  96. 124. 131. 185. 194. 128. 127. 186. 184. 188. 130.  71. 161.
 137.  99. 121. 187.  97.  90. 129. 113.]
____________________________________________________________________________________________________
[0 1]
____________________________________________________________________________________________________
[1.  3.1 2.6 0.  1.9 4.4 0.8 3.2 1.6 3.  0.7 4.2 1.5 2.2 1.1 0.3 0.4 0.6
 3.4 2.8 1.2 2.9 3.6 1.4 0.2 2.  5.6 0.9 1.8 6.2 4.  2.5 0.5 0.1 2.1 2.4
 3.8 2.3 1.3 3.5]
____________________________________________________________________________________________________
[2 0 1]
____________________________________________________________________________________________________
[ 2.  0.  1.  3. nan  4.]
____________________________________________________________________________________________________
[ 3.  2.  1.  0. nan]
____________________________________________________________________________________________________
[0 1]

In [79]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    1
chol        0
fbs         0
restecg     1
thalach     1
exang       0
oldpeak     0
slope       0
ca          2
thal        1
target      0
dtype: int64

In [81]:
lst=['trestbps','restecg','thalach','ca','thal']
for i in lst:
  print(df[i].unique())
  print(df[i].value_counts())

[125. 140. 145. 148. 138. 100. 114. 160. 120. 122. 112. 132. 118. 128.
  nan 124. 106. 104. 135. 130. 136. 180. 129. 150. 178. 146. 117. 152.
 154. 170. 134. 174. 144. 108. 123. 110. 142. 126. 192. 115.  94. 200.
 165. 102. 105. 155. 172. 164. 156. 101.]
trestbps
120.0    128
130.0    123
140.0    106
110.0     64
150.0     55
138.0     45
128.0     39
125.0     38
160.0     36
112.0     30
132.0     28
118.0     24
108.0     21
124.0     20
135.0     20
152.0     17
145.0     17
134.0     17
170.0     15
122.0     14
100.0     14
136.0     11
180.0     10
126.0     10
142.0      9
115.0      9
105.0      9
146.0      8
148.0      7
94.0       7
178.0      7
102.0      6
144.0      6
165.0      4
200.0      4
114.0      4
154.0      4
117.0      4
123.0      4
104.0      3
106.0      3
174.0      3
129.0      3
192.0      3
155.0      3
172.0      3
164.0      3
156.0      3
101.0      3
Name: count, dtype: int64
[nan  0.  1.  2.]
restecg
1.0    512
0.0    497
2.0     15
Name: count, dtype: int64
[168. 155. 125.  nan 106. 122. 140. 145. 144. 116. 136. 192. 156. 142.
 109. 162. 165. 148. 172. 173. 146. 179. 152. 117. 115. 112. 163. 147.
 182. 105. 150. 151. 169. 166. 178. 132. 160. 123. 139. 111. 180. 164.
 202. 157. 159. 170. 138. 175. 158. 126. 143. 141. 167.  95. 190. 118.
 103. 181. 108. 177. 134. 120. 171. 149. 154. 153.  88. 174. 114. 195.
 133.  96. 124. 131. 185. 194. 128. 127. 186. 184. 188. 130.  71. 161.
 137.  99. 121. 187.  97.  90. 129. 113.]
thalach
162.0    35
160.0    31
163.0    29
173.0    28
152.0    28
         ..
99.0      3
187.0     3
121.0     3
90.0      3
113.0     3
Name: count, Length: 91, dtype: int64
[ 2.  0.  1.  3. nan  4.]
ca
0.0    577
1.0    226
2.0    134
3.0     68
4.0     18
Name: count, dtype: int64
[ 3.  2.  1.  0. nan]
thal
2.0    543
3.0    410
1.0     64
0.0      7
Name: count, dtype: int64

In [83]:
df['trestbps']=df['trestbps'].fillna(df['trestbps'].mean())
df['trestbps'].isna().sum()

np.int64(0)

In [84]:
df['restecg']=df['restecg'].fillna(df['restecg'].mean())
df['restecg'].isna().sum()

np.int64(0)

In [85]:
df['thalach']=df['thalach'].fillna(df['thalach'].mean())
df['thalach'].isna().sum()

np.int64(0)

In [86]:
df['ca']=df['ca'].fillna(df['ca'].mode()[0])
df['ca'].isna().sum()

np.int64(0)

In [87]:
df['thal']=df['thal'].fillna(df['thal'].mean())
df['thal'].isna().sum()

np.int64(0)

In [88]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64